<?php

    function get_local_select_form(): string
    {

        return '<select id="campoLocal" name="campoLocal">
            
                '. get_local_options().'

             </select>';
    }
    
    function get_local_options(): string
    {
        return '<option value = "none"></option>
<option value = "Abrantes">Abrantes</option>
<option value = "Aguiar da Beira">Aguiar da Beira</option>
<option value = "Alandroal">Alandroal</option>
<option value = "Albergaria-a-Velha">Albergaria-a-Velha</option>
<option value = "Albufeira">Albufeira</option>
<option value = "Alcanena">Alcanena</option>
<option value = "Alcobaça">Alcobaça</option>
<option value = "Alcochete">Alcochete</option>
<option value = "Alcoutim">Alcoutim</option>
<option value = "Alcácer do Sal">Alcácer do Sal</option>
<option value = "Alenquer">Alenquer</option>
<option value = "Alfândega da Fé">Alfândega da Fé</option>
<option value = "Alijó">Alijó</option>
<option value = "Aljezur">Aljezur</option>
<option value = "Aljustrel">Aljustrel</option>
<option value = "Almada">Almada</option>
<option value = "Almeida">Almeida</option>
<option value = "Almeirim">Almeirim</option>
<option value = "Almodôvar">Almodôvar</option>
<option value = "Alpiarça">Alpiarça</option>
<option value = "Alter do Chão">Alter do Chão</option>
<option value = "Alvaiázere">Alvaiázere</option>
<option value = "Alvito">Alvito</option>
<option value = "Amadora">Amadora</option>
<option value = "Amarante">Amarante</option>
<option value = "Amares">Amares</option>
<option value = "Anadia">Anadia</option>
<option value = "Angra do Heroísmo">Angra do Heroísmo</option>
<option value = "Ansião">Ansião</option>
<option value = "Arcos de Valdevez">Arcos de Valdevez</option>
<option value = "Arganil">Arganil</option>
<option value = "Armamar">Armamar</option>
<option value = "Arouca">Arouca</option>
<option value = "Arraiolos">Arraiolos</option>
<option value = "Arronches">Arronches</option>
<option value = "Arruda dos Vinhos">Arruda dos Vinhos</option>
<option value = "Aveiro">Aveiro</option>
<option value = "Avis">Avis</option>
<option value = "Azambuja">Azambuja</option>
<option value = "Baião">Baião</option>
<option value = "Barcelos">Barcelos</option>
<option value = "Barrancos">Barrancos</option>
<option value = "Barreiro">Barreiro</option>
<option value = "Batalha">Batalha</option>
<option value = "Beja">Beja</option>
<option value = "Belmonte">Belmonte</option>
<option value = "Benavente">Benavente</option>
<option value = "Bombarral">Bombarral</option>
<option value = "Borba">Borba</option>
<option value = "Boticas">Boticas</option>
<option value = "Braga">Braga</option>
<option value = "Bragança">Bragança</option>
<option value = "Cabeceiras de Basto">Cabeceiras de Basto</option>
<option value = "Cadaval">Cadaval</option>
<option value = "Caldas da Rainha">Caldas da Rainha</option>
<option value = "Calheta (Madeira)">Calheta (Madeira)</option>
<option value = "Calheta (São Jorge)">Calheta (São Jorge)</option>
<option value = "Caminha">Caminha</option>
<option value = "Campo Maior">Campo Maior</option>
<option value = "Cantanhede">Cantanhede</option>
<option value = "Carrazeda de Ansiães">Carrazeda de Ansiães</option>
<option value = "Carregal do Sal">Carregal do Sal</option>
<option value = "Cartaxo">Cartaxo</option>
<option value = "Cascais">Cascais</option>
<option value = "Castanheira de Pêra">Castanheira de Pêra</option>
<option value = "Castelo Branco">Castelo Branco</option>
<option value = "Castelo de Paiva">Castelo de Paiva</option>
<option value = "Castelo de Vide">Castelo de Vide</option>
<option value = "Castro Daire">Castro Daire</option>
<option value = "Castro Marim">Castro Marim</option>
<option value = "Castro Verde">Castro Verde</option>
<option value = "Celorico da Beira">Celorico da Beira</option>
<option value = "Celorico de Basto">Celorico de Basto</option>
<option value = "Chamusca">Chamusca</option>
<option value = "Chaves">Chaves</option>
<option value = "Cinfães">Cinfães</option>
<option value = "Coimbra">Coimbra</option>
<option value = "Condeixa-a-Nova">Condeixa-a-Nova</option>
<option value = "Constância">Constância</option>
<option value = "Coruche">Coruche</option>
<option value = "Corvo">Corvo</option>
<option value = "Covilhã">Covilhã</option>
<option value = "Crato">Crato</option>
<option value = "Cuba">Cuba</option>
<option value = "Câmara de Lobos">Câmara de Lobos</option>
<option value = "Elvas">Elvas</option>
<option value = "Entroncamento">Entroncamento</option>
<option value = "Espinho">Espinho</option>
<option value = "Esposende">Esposende</option>
<option value = "Estarreja">Estarreja</option>
<option value = "Estremoz">Estremoz</option>
<option value = "Fafe">Fafe</option>
<option value = "Faro">Faro</option>
<option value = "Felgueiras">Felgueiras</option>
<option value = "Ferreira do Alentejo">Ferreira do Alentejo</option>
<option value = "Ferreira do Zêzere">Ferreira do Zêzere</option>
<option value = "Figueira da Foz">Figueira da Foz</option>
<option value = "Figueira de Castelo Rodrigo">Figueira de Castelo Rodrigo</option>
<option value = "Figueiró dos Vinhos">Figueiró dos Vinhos</option>
<option value = "Fornos de Algodres">Fornos de Algodres</option>
<option value = "Freixo de Espada à Cinta">Freixo de Espada à Cinta</option>
<option value = "Fronteira">Fronteira</option>
<option value = "Funchal">Funchal</option>
<option value = "Fundão">Fundão</option>
<option value = "Gavião">Gavião</option>
<option value = "Golegã">Golegã</option>
<option value = "Gondomar">Gondomar</option>
<option value = "Gouveia">Gouveia</option>
<option value = "Grândola">Grândola</option>
<option value = "Guarda">Guarda</option>
<option value = "Guimarães">Guimarães</option>
<option value = "Góis">Góis</option>
<option value = "Horta">Horta</option>
<option value = "Idanha-a-Nova">Idanha-a-Nova</option>
<option value = "Lagoa (Algarve)">Lagoa (Algarve)</option>
<option value = "Lagoa (São Miguel)">Lagoa (São Miguel)</option>
<option value = "Lagos">Lagos</option>
<option value = "Lajes das Flores">Lajes das Flores</option>
<option value = "Lajes do Pico">Lajes do Pico</option>
<option value = "Lamego">Lamego</option>
<option value = "Leiria">Leiria</option>
<option value = "Lisboa">Lisboa</option>
<option value = "Loulé">Loulé</option>
<option value = "Loures">Loures</option>
<option value = "Lourinhã">Lourinhã</option>
<option value = "Lousada">Lousada</option>
<option value = "Lousã">Lousã</option>
<option value = "Macedo de Cavaleiros">Macedo de Cavaleiros</option>
<option value = "Machico">Machico</option>
<option value = "Madalena">Madalena</option>
<option value = "Mafra">Mafra</option>
<option value = "Maia">Maia</option>
<option value = "Mangualde">Mangualde</option>
<option value = "Manteigas">Manteigas</option>
<option value = "Marco de Canaveses">Marco de Canaveses</option>
<option value = "Marinha Grande">Marinha Grande</option>
<option value = "Marvão">Marvão</option>
<option value = "Matosinhos">Matosinhos</option>
<option value = "Mação">Mação</option>
<option value = "Mealhada">Mealhada</option>
<option value = "Meda">Meda</option>
<option value = "Melgaço">Melgaço</option>
<option value = "Mesão Frio">Mesão Frio</option>
<option value = "Mira">Mira</option>
<option value = "Miranda do Corvo">Miranda do Corvo</option>
<option value = "Miranda do Douro">Miranda do Douro</option>
<option value = "Mirandela">Mirandela</option>
<option value = "Mogadouro">Mogadouro</option>
<option value = "Moimenta da Beira">Moimenta da Beira</option>
<option value = "Moita">Moita</option>
<option value = "Monchique">Monchique</option>
<option value = "Mondim de Basto">Mondim de Basto</option>
<option value = "Monforte">Monforte</option>
<option value = "Montalegre">Montalegre</option>
<option value = "Montemor-o-Novo">Montemor-o-Novo</option>
<option value = "Montemor-o-Velho">Montemor-o-Velho</option>
<option value = "Montijo">Montijo</option>
<option value = "Monção">Monção</option>
<option value = "Mora">Mora</option>
<option value = "Mortágua">Mortágua</option>
<option value = "Moura">Moura</option>
<option value = "Mourão">Mourão</option>
<option value = "Murtosa">Murtosa</option>
<option value = "Murça">Murça</option>
<option value = "Mértola">Mértola</option>
<option value = "Nazaré">Nazaré</option>
<option value = "Nelas">Nelas</option>
<option value = "Nisa">Nisa</option>
<option value = "Nordeste">Nordeste</option>
<option value = "Odemira">Odemira</option>
<option value = "Odivelas">Odivelas</option>
<option value = "Oeiras">Oeiras</option>
<option value = "Oleiros">Oleiros</option>
<option value = "Olhão">Olhão</option>
<option value = "Oliveira de Azeméis">Oliveira de Azeméis</option>
<option value = "Oliveira de Frades">Oliveira de Frades</option>
<option value = "Oliveira do Bairro">Oliveira do Bairro</option>
<option value = "Oliveira do Hospital">Oliveira do Hospital</option>
<option value = "Ourique">Ourique</option>
<option value = "Ourém">Ourém</option>
<option value = "Ovar">Ovar</option>
<option value = "Palmela">Palmela</option>
<option value = "Pampilhosa da Serra">Pampilhosa da Serra</option>
<option value = "Paredes">Paredes</option>
<option value = "Paredes de Coura">Paredes de Coura</option>
<option value = "Paços de Ferreira">Paços de Ferreira</option>
<option value = "Pedrógão Grande">Pedrógão Grande</option>
<option value = "Penacova">Penacova</option>
<option value = "Penafiel">Penafiel</option>
<option value = "Penalva do Castelo">Penalva do Castelo</option>
<option value = "Penamacor">Penamacor</option>
<option value = "Penedono">Penedono</option>
<option value = "Penela">Penela</option>
<option value = "Peniche">Peniche</option>
<option value = "Peso da Régua">Peso da Régua</option>
<option value = "Pinhel">Pinhel</option>
<option value = "Pombal">Pombal</option>
<option value = "Ponta Delgada">Ponta Delgada</option>
<option value = "Ponta do Sol">Ponta do Sol</option>
<option value = "Ponte da Barca">Ponte da Barca</option>
<option value = "Ponte de Lima">Ponte de Lima</option>
<option value = "Ponte de Sor">Ponte de Sor</option>
<option value = "Portalegre">Portalegre</option>
<option value = "Portel">Portel</option>
<option value = "Portimão">Portimão</option>
<option value = "Porto">Porto</option>
<option value = "Porto Moniz">Porto Moniz</option>
<option value = "Porto Santo">Porto Santo</option>
<option value = "Porto de Mós">Porto de Mós</option>
<option value = "Povoação">Povoação</option>
<option value = "Praia da Vitória">Praia da Vitória</option>
<option value = "Proença-a-Nova">Proença-a-Nova</option>
<option value = "Póvoa de Lanhoso">Póvoa de Lanhoso</option>
<option value = "Póvoa de Varzim">Póvoa de Varzim</option>
<option value = "Redondo">Redondo</option>
<option value = "Reguengos de Monsaraz">Reguengos de Monsaraz</option>
<option value = "Resende">Resende</option>
<option value = "Ribeira Brava">Ribeira Brava</option>
<option value = "Ribeira Grande">Ribeira Grande</option>
<option value = "Ribeira de Pena">Ribeira de Pena</option>
<option value = "Rio Maior">Rio Maior</option>
<option value = "Sabrosa">Sabrosa</option>
<option value = "Sabugal">Sabugal</option>
<option value = "Salvaterra de Magos">Salvaterra de Magos</option>
<option value = "Santa Comba Dão">Santa Comba Dão</option>
<option value = "Santa Cruz">Santa Cruz</option>
<option value = "Santa Cruz da Graciosa">Santa Cruz da Graciosa</option>
<option value = "Santa Cruz das Flores">Santa Cruz das Flores</option>
<option value = "Santa Maria da Feira">Santa Maria da Feira</option>
<option value = "Santa Marta de Penaguião">Santa Marta de Penaguião</option>
<option value = "Santana">Santana</option>
<option value = "Santarém">Santarém</option>
<option value = "Santiago do Cacém">Santiago do Cacém</option>
<option value = "Santo Tirso">Santo Tirso</option>
<option value = "Sardoal">Sardoal</option>
<option value = "Seia">Seia</option>
<option value = "Seixal">Seixal</option>
<option value = "Sernancelhe">Sernancelhe</option>
<option value = "Serpa">Serpa</option>
<option value = "Sertã">Sertã</option>
<option value = "Sesimbra">Sesimbra</option>
<option value = "Setúbal">Setúbal</option>
<option value = "Sever do Vouga">Sever do Vouga</option>
<option value = "Silves">Silves</option>
<option value = "Sines">Sines</option>
<option value = "Sintra">Sintra</option>
<option value = "Sobral de Monte Agraço">Sobral de Monte Agraço</option>
<option value = "Soure">Soure</option>
<option value = "Sousel">Sousel</option>
<option value = "Sátão">Sátão</option>
<option value = "São Brás de Alportel">São Brás de Alportel</option>
<option value = "São João da Madeira">São João da Madeira</option>
<option value = "São João da Pesqueira">São João da Pesqueira</option>
<option value = "São Pedro do Sul">São Pedro do Sul</option>
<option value = "São Roque do Pico">São Roque do Pico</option>
<option value = "São Vicente">São Vicente</option>
<option value = "Tabuaço">Tabuaço</option>
<option value = "Tarouca">Tarouca</option>
<option value = "Tavira">Tavira</option>
<option value = "Terras de Bouro">Terras de Bouro</option>
<option value = "Tomar">Tomar</option>
<option value = "Tondela">Tondela</option>
<option value = "Torre de Moncorvo">Torre de Moncorvo</option>
<option value = "Torres Novas">Torres Novas</option>
<option value = "Torres Vedras">Torres Vedras</option>
<option value = "Trancoso">Trancoso</option>
<option value = "Trofa">Trofa</option>
<option value = "Tábua">Tábua</option>
<option value = "Vagos">Vagos</option>
<option value = "Vale de Cambra">Vale de Cambra</option>
<option value = "Valença">Valença</option>
<option value = "Valongo">Valongo</option>
<option value = "Valpaços">Valpaços</option>
<option value = "Velas">Velas</option>
<option value = "Vendas Novas">Vendas Novas</option>
<option value = "Viana do Alentejo">Viana do Alentejo</option>
<option value = "Viana do Castelo">Viana do Castelo</option>
<option value = "Vidigueira">Vidigueira</option>
<option value = "Vieira do Minho">Vieira do Minho</option>
<option value = "Vila Flor">Vila Flor</option>
<option value = "Vila Franca de Xira">Vila Franca de Xira</option>
<option value = "Vila Franca do Campo">Vila Franca do Campo</option>
<option value = "Vila Nova da Barquinha">Vila Nova da Barquinha</option>
<option value = "Vila Nova de Cerveira">Vila Nova de Cerveira</option>
<option value = "Vila Nova de Famalicão">Vila Nova de Famalicão</option>
<option value = "Vila Nova de Foz Côa">Vila Nova de Foz Côa</option>
<option value = "Vila Nova de Gaia">Vila Nova de Gaia</option>
<option value = "Vila Nova de Paiva">Vila Nova de Paiva</option>
<option value = "Vila Nova de Poiares">Vila Nova de Poiares</option>
<option value = "Vila Pouca de Aguiar">Vila Pouca de Aguiar</option>
<option value = "Vila Real">Vila Real</option>
<option value = "Vila Real de Santo António">Vila Real de Santo António</option>
<option value = "Vila Velha de Ródão">Vila Velha de Ródão</option>
<option value = "Vila Verde">Vila Verde</option>
<option value = "Vila Viçosa">Vila Viçosa</option>
<option value = "Vila de Rei">Vila de Rei</option>
<option value = "Vila do Bispo">Vila do Bispo</option>
<option value = "Vila do Conde">Vila do Conde</option>
<option value = "Vila do Porto">Vila do Porto</option>
<option value = "Vimioso">Vimioso</option>
<option value = "Vinhais">Vinhais</option>
<option value = "Viseu">Viseu</option>
<option value = "Vizela">Vizela</option>
<option value = "Vouzela">Vouzela</option>
<option value = "nome_concelho">nome_concelho</option>
<option value = "Águeda">Águeda</option>
<option value = "Évora">Évora</option>
<option value = "Ílhavo">Ílhavo</option>
<option value = "Óbidos">Óbidos</option>';
    }
